### ISSUE TITLE
saying invalid username and/or password

### ISSUE THREAD

**Issue by jkawamoto4** [skiptomyliu/milkshake#42]
I am trying to login to milkshake and it keeps telling me invalid username/password but it is not wrong as I was already logged in earlier in the day. I have reset my password with pandora and it still is not working. I have uninstalled the app and reinstalled it and it is still giving me this error. not really sure what do from here, thanks.

**Comment by loupgrru** [comment]
Same thing here.  Started yesterday.

**Comment by rmw1221** [comment]
Same issue here as well... discovered today

**Comment by dauhrman** [comment]
Same issue.  Started today.  Name and password still work on Pandora website.  Deleted and redownloaded from Apple App Store, new copy picked up same credentials from my computer, still refused to validate.  Tried multiple times to manually input to no avail.

**Comment by sygibson** [comment]
I can confirm that on Tue Feb 9 2021 in the afternoon (PST) - my Milkshake app also can no longer login.  Receiving the same `Invalid username and/or password` error.

I verified I can log in to my Pandora account from the miserable P.O.S. Mac app that Pandora makes, and via the web page.

**Comment by afterthetone** [comment]
Discovered same thing today. This is still an issue.

**Comment by ReallyRandy** [comment]
Same here. Pandora must have changed something in their API.

**Comment by eric997tt** [comment]
Delete your password and sign in. I'm not sure why it works, but I deleted my password and accidentally clicked "login" and it started working.

**Comment by ReallyRandy** [comment]
> Delete your password and sign in. I'm not sure why it works, but I deleted my password and accidentally clicked "login" and it started working.

Wow, that worked, Thanks!

**Comment by dauhrman** [comment]
Removing password worked!  Still needs to be fixed, but this will do for now.

Thanks much.

**Comment by loupgrru** [comment]
Fortuitous mistakes for the win!  Thanks, Eric.

**Comment by loupgrru** [comment]
It stopped working again.  Going without a password is no longer letting me in.  Anyone else having this problem?

**Comment by dauhrman** [comment]
Yes.

**Comment by z4am** [comment]
Just a note that as of today, deleting your password still works. First try to sign in with your password, then delete it and log in. 
One of these days I'll learn some Swift so I can get the volume, crossfade, and spectrum settings to persist, but still one of my favorite apps.

**Comment by loupgrru** [comment]
I had deleted it after it stopped working.  I just tried to reinstall after seeing z4am’s comment, but apparently it’s no longer available, or at least not in the US.

**Comment by z4am** [comment]
Hi @loupgrru, the .DMG installer is still available right here https://github.com/skiptomyliu/milkshake
To test it, I just downloaded and installed it on my son's Macbook and logged in successfully. :)

**Comment by loupgrru** [comment]
Hi Skip,

I just tried and got the same message, attached a screen shot of that message.  Thanks for responding, though.

Mark Stewart
N2020 Cty Hwy H, Lot 508
Lake Geneva, WI 53147
262-812-9517 
-----Original Message-----

**Comment by djames42** [comment]
FWIW, this trick no longer seems to work. I've tried it on both my Macs and have also tried deleting the app and associated preference and container data.

Would love to fork this and get it working again - I love the small footprint and the crossfade - but I just don't have time right now.

**Comment by djames42** [comment]
Well bad news. Looks like the developer token used by the app has expired and needs to be renewed. When I step through the code, I'm seeing the following response from Pandora when I attempt to authenticate:
`  "message" : "Auth Token is Expired - ...[token hidden here, even though it's available in the source code]"	`

I tried to register a new developer account with Pandora so I could generate a new token, but they're not accepting new requests at this time. At this point, only the original developer can sort this out and he's gone MIA from this project so I don't see that likely happening. It seems a bit silly that Pandora would expire an application token that would require a number of apps to be redistributed in order to function again. But it also looks like Pandora may be moving from a direct username/password login to an end-user token authentication so they may have deprecated these legacy Auth Tokens on purpose to force developers into updating their code.

It seems like the reason this was working for a period of time with a blank password is that a cookie was stored locally that eliminated the need to authenticate every time the app was launched. When those cookies expired, the app would fall back to authenticating and fail due to the expired Auth Token.

**Comment by loupgrru** [comment]
Thanks for trying. 
 
Mark Stewart
N2020 Cty Hwy H, Lot 508
Lake Geneva, WI 53147
262-812-9517 
-----Original Message-----

**Comment by skiptomyliu** [comment]
@djames42 @loupgrru 

Thanks for helping dig here.  I took a look this afternoon and it looks like Pandora made some changes into their login REST API.    The tl;dr there is that there are some additional fields that are required where I cannot grok exactly how it's being generated.  

There's an unofficial Pandora API doc here:  https://6xq.net/pandora-apidoc/json/ 

Note that there are two APIs, a REST API and a JSON API v5.  Milkshake was using the REST API which is what the browser uses as well.

What needs to happen is to migrate auth to the JSON API v5 instead.  I'm unsure exactly if that is the only thing that needs to be done and if the token generated by the JSON API can be used with the REST API.  Either way, I'll take a look but hope to have a update with what I find.

**Comment by skiptomyliu** [comment]
Bummer -- so it looks like Pandora added some anti bot measures which is why this has been breaking.  Migrating to the JSON API v5 API would be needed.  However, unfortunately I can't commit to it at this time.  :\

Dropping some rough notes for myself (and potentially others if they want to dig in).
1. Login as partner https://6xq.net/pandora-apidoc/json/partners/#partners using the partner password: https://6xq.net/pandora-apidoc/json/partners/#android

2. Using the auth token generated, then login as a user: https://6xq.net/pandora-apidoc/json/authentication/#user-login

The generated token seems to work with the JSON API  based on reports from https://github.com/PromyLOPh/pandora-apidoc/issues/45

The heavy lift for this change is introducing CryptoSwift into the project so we can encrypt the payloads for the user login.

**Comment by skiptomyliu** [comment]
I'm working on a fix.  This PR is working https://github.com/skiptomyliu/milkshake/pull/45 and contains an updated dmg install with the fix.

Cleaning up some things before I merge.

**Comment by skiptomyliu** [comment]
v1.1.0 fix has finally been released to the appstore: 
https://apps.apple.com/us/app/milkshake-player-for-pandora/id1440379601?mt=12

v1.1.1 it's also available for download which fixes the search results:
https://github.com/skiptomyliu/milkshake/releases

I'll push another round of fixes to the appstore soon.  Thanks immensely for being incredibly patient on this.  Hoping to finally start doing releases on a more regular cadence.

**Comment by djames42** [comment]
This is brilliant! Thank you so much for taking the time to resolve the login issue.

I love that this is open source, but honestly I would've happily paid for this app. I use it all day, every day. Maybe a paid iOS version?

**Comment by loupgrru** [comment]
Thanks, Dean!

Mark Stewart
N2020 Cty Hwy H, Lot 508
Lake Geneva, WI 53147
262-812-9517 
-----Original Message-----

**Comment by skiptomyliu** [comment]
> This is brilliant! Thank you so much for taking the time to resolve the login issue.
> 
> I love that this is open source, but honestly I would've happily paid for this app. I use it all day, every day. Maybe a paid iOS version?

@djames42 thanks for the very kind words!  I love Pandora and building things, happy to share something that ya'll enjoy!  

Keeping it free keeps it as a hobby and the stress levels down 😂

**Comment by feego16** [comment]
its not working when I log in my email or password.

**Comment by feego16** [comment]
How is it working for you guys?

**Comment by djames42** [comment]
> How is it working for you guys?

I just tried it and it's working fine for me.

**Comment by feego16** [comment]
how did you get it to work? I tried to put in my email and password and its not working.

**Comment by feego16** [comment]
<img width="305" alt="Screenshot 2023-10-23 at 12 47 18 PM" src="https://github.com/skiptomyliu/milkshake/assets/16760346/bfdbd014-7a8b-4a51-a8b3-c233a31c1b57">

**Comment by feego16** [comment]
I logged into Pandora ok but when I try to log in milkshake its not logging me in.

**Comment by djames42** [comment]
Odd. my login info was prepopulated from prior logins. I clicked the Login button and got my list of stations, which play just fine.

**Comment by feego16** [comment]
How did you get those loggins? I used the login I created years ago. How do u populate loggins? Im not good at coding so I'm not sure if its a code thing.

**Comment by feego16** [comment]
Is there a special password I should enter for mine to work? I don't know what I am doing wrong.

**Comment by djames42** [comment]
No code thing. The login and password are the same that you would use to log in directly to Pandora. The credentials are saved after logging in so now all I need to do is click the login button.

I'm not sure why your login isn't working. If I have time, I will launch a MacOS virtual machine and try logging in fresh to see if my credentials work okay for an initial login.

**Comment by djames42** [comment]
I had a VM all ready to go so I just tried logging in fresh. When this issue first cropped up, my existing login credentials worked for a time but I was unable to log in with a new install. I thought maybe a similar issue might be happening.

Alas, I downloaded the Milkshake DMG from here into the VM, launched the app, and manually typed my login credentials and it worked okay. Perhaps there are characters in your password the app isn't able to pass through the API okay, but otherwise I can't fathom why your login works on the web but not in the app.

**Comment by feego16** [comment]
I am not using the app from the appstore. Im using the one from this github. I don't know why mine isn't working. I deleted and downloaded it twice and still nothing. It used to work with no password until it stopped working again. I read ur past messages and noticed its working for u guys and then I downloaded it again and entered both email and password but still nothing.

**Comment by djames42** [comment]
I also use the version from Github. I would normally suggest deleting the application preference file from either ~/Library/Preferences or ~/Library/Application Support but it appears Milkshake does not use this. Looking at the code, it pulls the login and password from the Keychain, so you might quit Milkshake, launch Keychain Access, search for Milkshake, and delete that entry. Then close Keychain and relaunch Milkshake and enter your Pandora login and password again.

I suspect this will not do anything, but I cannot think of what else to try.

**Comment by feego16** [comment]
its working now. It seems I have to use a VPN thanks for ur time tho I really appreciate u trying to help!
